name: auto-encoder
channels:
- conda-forge
dependencies:
- python=3.8.5
- pip:
  - mlflow
  - cloudpickle==1.2.2
  - dataclasses==0.6
  - dill==0.3.1.1
  - lz4==3.1.0
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - torch==1.12.0
  - tqdm==4.64.0
  - typing==3.7.4.3
  - inference-schema==1.5
  - azureml-defaults==1.47.0
