$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: job_schedule
display_name: Simple recurrence job schedule
description: a simple hourly recurrence job schedule

trigger:
  type: recurrence
  frequency: day #can be minute, hour, day, week, month
  interval: 1 #every day
  schedule:
    hours: [10]
    minutes: [30]
  time_zone: "Pacific Standard Time" # optional - default will be UTC

create_job: ./training_pipeline.yml
# create_job: azureml:simple-pipeline-job
