name: isolation-forest
channels:
- conda-forge
dependencies:
- python=3.8.5
- pip
- pip:
  - mlflow
  - cloudpickle==1.2.2
  - dataclasses==0.6
  - lz4==3.1.0
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - typing==3.7.4.3
  - inference-schema==1.5
name: mlflow-env

